pipeline {
  agent any

  tools {
      go 'go1.16.4'
  }
  environment {
    GO114MODULE = 'on'
    CGO_ENABLED = 0
    GOPATH = "${JENKINS_HOME}/jobs/${JOB_NAME}/builds/${BUILD_ID}"
  }
  stages {
    stage('Pre Test') {
      steps {
          echo 'Installing dependenciess'
          sh 'go version'
          sh '''
          cd ./cidr_convert_api/go/
          go get -u golang.org/x/lint/golint
          '''
          sh '''
            go get github.com/Pepegasca/goop
          '''
          // withEnv(["PATH+GO=${GOPATH}/bin"]) {
          //   sh '''
          //   pwd
          //   ls
          //   cd ./cidr_convert_api/go/
          //   chmod -R 777 .
          //   goop install
          //   '''
          // }
      }
    }
    stage('Build2') {
      steps {
        sh '''
        cd ./cidr_convert_api/go/
        sudo docker-compose up -d --build
        '''
      }
    }

    stage('Test') {
      steps {
          echo 'Running vetting'
          sh '''
          cd ./cidr_convert_api/go/
          go vet .'''
          echo 'Running test'
          sh '''
          cd ./cidr_convert_api/go/
          go test
          '''
      }
    }
  }
}
