pipeline {
  agent any

  tools {
      go 'go1.16.4'
  }
  stages {
    stage('Pre Test') {
      steps {
        withEnv(["GOROOT=${root}", "PATH+GO=${root}/bin"]) {
          echo 'Installing dependencies'
          sh 'go version'
          sh '''
          cd ./cidr_convert_api/go/
          go get -u golang.org/x/lint/golint'''
        }
      }
    }
    stage('Build2') {
      steps {
        sh '''
        cd ./cidr_convert_api/go/
        sudo docker-compose up -d --build
        '''
      }
    }

    stage('Test') {
      steps {
          echo 'Running vetting'
          sh '''
          cd ./cidr_convert_api/go/
          go vet .'''
          echo 'Running linting'
          sh '''
          cd ./cidr_convert_api/go/
          golint .
          '''
          echo 'Running test'
          sh '''
          cd ./cidr_convert_api/go/
          go test
          '''
      }
    }
  }
}
