apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: go-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
      - name: go-ms-container
        image: roquebajosexto/devops-roque:lastest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ms-cluster-svc
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer